//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balda.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageSources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageSources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Balda.Resources.MessageSources", typeof(MessageSources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите слово.
        /// </summary>
        internal static string EnterTheWordMessage {
            get {
                return ResourceManager.GetString("EnterTheWordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя пользователя.
        /// </summary>
        internal static string EnterUsernameMessage {
            get {
                return ResourceManager.GetString("EnterUsernameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string ErrorMessagePrefix {
            get {
                return ResourceManager.GetString("ErrorMessagePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игра окончена победитель.
        /// </summary>
        internal static string GameEndFirstPartMessage {
            get {
                return ResourceManager.GetString("GameEndFirstPartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на очков).
        /// </summary>
        internal static string GameEndSecondPartMessage {
            get {
                return ResourceManager.GetString("GameEndSecondPartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В игре уже два игрока.
        /// </summary>
        internal static string GameFullMessage {
            get {
                return ResourceManager.GetString("GameFullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игра не найдена.
        /// </summary>
        internal static string GameNotFoundMessage {
            get {
                return ResourceManager.GetString("GameNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на id вашей игры было скопированно в буфер обмена.
        /// </summary>
        internal static string IdWasCopiedMessage {
            get {
                return ResourceManager.GetString("IdWasCopiedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат id.
        /// </summary>
        internal static string IncorrectIdFormatMessage {
            get {
                return ResourceManager.GetString("IncorrectIdFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин должен бытиь минимум четыре буквы в длину и не содержать спец символов.
        /// </summary>
        internal static string IncorrectLogginMessage {
            get {
                return ResourceManager.GetString("IncorrectLogginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль должен быть в длину не менее десяти символов.
        /// </summary>
        internal static string IncorrectPasswordMessage {
            get {
                return ResourceManager.GetString("IncorrectPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на неверный логин или пароль.
        /// </summary>
        internal static string InvalidLoginPasswordMessage {
            get {
                return ResourceManager.GetString("InvalidLoginPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сейчас не ваш ход.
        /// </summary>
        internal static string ItsNotYourTurnMessage {
            get {
                return ResourceManager.GetString("ItsNotYourTurnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этот логин уже занят.
        /// </summary>
        internal static string LogginInUseMessage {
            get {
                return ResourceManager.GetString("LogginInUseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите логин.
        /// </summary>
        internal static string LoginRequiredMessage {
            get {
                return ResourceManager.GetString("LoginRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слово должно содержать добавленную букву.
        /// </summary>
        internal static string MustContainMessage {
            get {
                return ResourceManager.GetString("MustContainMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль.
        /// </summary>
        internal static string PasswordRequiredMessage {
            get {
                return ResourceManager.GetString("PasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароли не соответсвуют.
        /// </summary>
        internal static string PasswordsNotEqualMessage {
            get {
                return ResourceManager.GetString("PasswordsNotEqualMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы успешно зарегистрировались.
        /// </summary>
        internal static string RegistrationSuccsessMessage {
            get {
                return ResourceManager.GetString("RegistrationSuccsessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь не найден.
        /// </summary>
        internal static string UserNotFoundMessage {
            get {
                return ResourceManager.GetString("UserNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Это слово уже было использованно.
        /// </summary>
        internal static string WasUsedWordMessage {
            get {
                return ResourceManager.GetString("WasUsedWordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Такого слова не существует.
        /// </summary>
        internal static string WordDoesntExistMessage {
            get {
                return ResourceManager.GetString("WordDoesntExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уже в игре.
        /// </summary>
        internal static string YouAlreadyInGameMessage {
            get {
                return ResourceManager.GetString("YouAlreadyInGameMessage", resourceCulture);
            }
        }
    }
}
