FROM postgres:latest

ENV POSTGRES_USER=balda
ENV POSTGRES_PASSWORD=balda
ENV POSTGRES_DB=usersbd

# Expose the default PostgreSQL port
EXPOSE 5432

# You can add custom initialization scripts here.
# For example, to create tables or seed data:
# COPY ./init.sql /docker-entrypoint-initdb.d/
